config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'sports/kensaku' => 'sports#kensaku'
  resources :sports
  resources :sindans
  root 'topics#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sport.rb
class Sport < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sindans_controller.rb
class SindansController < ApplicationController
    def index 
    end
    
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
    def index
        if params[:search] == nil
          @sports= Sport.all
        elsif params[:search] == ''
          @sports= Sport.all
        else
          #部分検索
          @sports = Sport.where("name LIKE ? ",'%' + params[:search] + '%')
        end
  
    end
    def new
      @sport = Sport.new
    end

    def kensaku
      if params[:search] == nil
        @sports= Sport.all
      elsif params[:search] == ''
        @sports= Sport.all
      else
        #部分検索
        @sports = Sport.where("name LIKE ? ",'%' + params[:search] + '%')
      end

    end    
    
    def show
      @sport = Sport.find(params[:id])
    end

      def create
        sport = Sport.new(sport_params)
        if sport.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
    

      def edit
        @sport = Sport.find(params[:id])
      end

      def update
        sport = Sport.find(params[:id])
        if sport.update(sport_params)
          redirect_to :action => "show", :id => sport.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        sport = Sport.find(params[:id])
        sport.destroy
        redirect_to action: :index
      end

      private
      def sport_params
        params.require(:sport).permit(:name, :address, :about, :image)
      end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    def index
        @sports = Sport.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sindans_helper.rb
module SindansHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geeksport</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sindans/index.html.erb
<header id="commonHeader">
<section id="flowsHead" class="wf-mplus1p">あなたにあった運動場所が1分でわかる</section>
<section id="flows" class="wf-mplus1p">〇〇診断</section>
</header>

<div id="wrapper">
   <div class="sense">
        <article id="pageBody">

            <div class="point_box">
            <div class="box">
            <div class="txt">
            <p>1分だけ下記の質問に答えてみてください。あなたにぴったりの運動場所がわかります!</p>
            </div>
            </div>
            </div>


            <ul class="qalist wf-mplus1p">

            <li id="1" class="question">
                <a name="#1"></a>
                <div class="qbox"><span  class="q">Q1.</span>都心からの距離は？</div>
                <div class="qabox">
                    <a href="#2" onclick="show(2)" class="qabtn"><div class="btnBox btnBox_y">近い</div></a>
                    <a href="#3" onclick="show(3)" class="qabtn"><div class="btnBox btnBox_n">遠い</div></a>
                </div>
            </li>
            <li id="2" class="question" style="display:none;">
                <a name="#"></a>
                <div class="qbox"><span  class="q">Q2.</span>運動重視とその他の目的（買い物や景観）重視どちらですか？</div>
                <div class="qabox">
                    <a href="#101" onclick="show(101)" class="qabtn"><div class="btnBox btnBox_y">運動</div></a>
                    <a href="#102" onclick="show(102)" class="qabtn"><div class="btnBox btnBox_n">他も</div></a>
                </div>
            </li>
            <li id="3" class="question" style="display:none;">
                <a name="#"></a>
                <div class="qbox"><span  class="q">Q.</span>運動重視とその他の目的（買い物や景観）重視どちらですか？</div>
                <div class="qabox">
                    <a href="#103" onclick="show(103)" class="qabtn"><div class="btnBox btnBox_y">運動</div></a>
                    <a href="#104" onclick="show(104)" class="qabtn"><div class="btnBox btnBox_n">他も</div></a>
                </div>
            </li>
            </ul>

            <div class="answerList">

                <div id="101" style="display:none;" class="answer point_box">
                    <div class="box">
                        <div class="title">
                        <p>あなたに勧める運動場所は<span class="fs-18"><span class="bg-y">『浦安市運動公園』</span></span>です！</p>
                        </div>
                    <div class="txt">
                        <div class="img">
                        <%= image_tag '' %></div>
                        <p>説明会文「ディズニーリゾートからも近い！様々なスポーツが楽しめる公園」</p>
<p>住所：千葉県浦安市舞浜2-27</p>
<p>アクセス：JR京葉線「舞浜」駅から徒歩10分</p>
<p>詳細を記載</p>
                        <p><a href="#" class="square_btn">もっと詳しくみる</a></p>
                    </div>
                    </div>
                </div>
                <div id="102" style="display:none;" class="answer point_box">
                    <div class="box">
                        <div class="title">
                        <p>あなたに勧める運動場所は<span class="fs-18"><span class="bg-y">『県立幕張海浜公園』</span></span>です！</p>
                        </div>
                    <div class="txt">
                        <div class="img">
                        <%= image_tag '' %></div>
                        <p>説明文「幕張新都心の中心部！海にも歩いていける公園」</p>
<p>住所：千葉県千葉市美浜区ひび野2丁目116</p>
<p>アクセス：JR京葉線「海浜幕張」駅南口から徒歩約10分</p>
<p>詳細を記載</p>
                        <p><a href="#" class="square_btn">もっと詳しくみる</a></p>
                    </div>
                    </div>
                </div>
                <div id="103" style="display:none;" class="answer point_box">
                    <div class="box">
                        <div class="title">
                        <p>あなたに勧める運動場所は<span class="fs-18"><span class="bg-y">『昭和の森』</span></span>です！</p>
                        </div>
                    <div class="txt">
                        <div class="img">
                        <%= image_tag '' %></div>
                        <p>説明文「千葉県でも最大の大きさを誇る！ランニングコースやアスレチックも豊富な公園」</p>
<p>住所：千葉県千葉市緑区土気町34</p>
<p>アクセス：JR外房線「土気」駅南口から徒歩30分</p>
<p>詳細を記載</p>
                        <p><a href="#" class="square_btn">もっと詳しくみる</a></p>
                    </div>
                    </div>
                </div>
                <div id="104" style="display:none;" class="answer point_box">
                    <div class="box">
                        <div class="title">
                        <p>あなたに勧める運動場所は<span class="fs-18"><span class="bg-y">『清水渓流広場』説明文「タイトル」</span></span>です！</p>
                        </div>
                    <div class="txt">
                        <div class="img">
                        <%= image_tag '' %></div>
                        <p>説明文「千葉県の秘境！インスタ映え間違いなしのスポットがある公園」</p>
<p>住所：千葉県君津市笹1954</p>
<p>アクセス：JR久留里線「上総亀山」駅からタクシーで15分</p>
<p>詳細を記載</p>
                    </div>
                    </div>
                </div>



        </article>
    </div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>

<script type="text/javascript">
$(function(){
   $('a[href^=#]').click(function() {
      var speed = 600;
      var href= $(this).attr("href");
      var target = $(href == "#" || href == "" ? 'html' : href);
      var position = target.offset().top;
      $('body,html').animate({scrollTop:position}, speed, 'swing');
      return false;
   });
});
$(function(){
    h = $(window).height();
    h = h-30;
    $(".question").css("min-height", h + "px");
    $(".answerList .box").css("min-height", h + "px");
    
});
function show(idName){ 
    $("#" + idName).show();
}

</script>


</body>
</html>

app/views/sports/edit.html.erb
<%= form_for @sport do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, :size => 140 %>
    </div>

    <div class="field">
      <%= f.label :address %>
      <%= f.text_field :address, :size => 140 %>
    </div>

    <div class="field">
      <%= f.label :about %>
      <%= f.text_field :about, :size => 140 %>
    </div>
  
    <!--ここから-->
    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    <!--ここまで-->
  
    <%= f.submit "投稿する" %>
  <% end %>

app/views/sports/index.html.erb
<div class="teewts-container">
<% @sports.each do |t| %>
  <div class="tweet">
  

    <%= image_tag t.image_url, size: "250x200" if t.image? %>

      <%= t.name %>
      <%= t.address %>
      
      <%= t.about %>
    <%= t.created_at %>
    <%= link_to "詳細へ", sport_path(t.id) %>
    <%= link_to "編集する", edit_sport_path(t.id) %>
    <%= button_to "削除する", sport_path(t.id), method: :delete %>
  </div>
<% end %>
</div>
<h3>Tweet一覧</h3>

<!--ここから-->

<!--ここまで-->

<%= link_to "新規投稿へ", new_sport_path %>

</div>

app/views/sports/kensaku.html.erb
<h1>GeekSports</h1>
<h3>Tweet一覧</h3>

<h3>投稿を検索</h3>
 <%= form_tag({controller:"sports",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>

app/views/sports/new.html.erb
<%= form_for @sport do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, :size => 140 %>
    </div>

    <div class="field">
      <%= f.label :address %>
      <%= f.text_field :address, :size => 140 %>
    </div>

    <div class="field">
      <%= f.label :about %>
      <%= f.text_field :about, :size => 140 %>
    </div>
  
    <!--ここから-->
    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    <!--ここまで-->
  
    <%= f.submit "投稿する" %>
  <% end %>

app/views/sports/show.html.erb
<p><%= @sport.name %></p>
<p><%= @sport.about %></p>

app/views/topics/index.html.erb
Hello World!
<%= link_to '診断はこちらから',  sindans_path, class: "link" %>
<%= link_to '検索はこちらから',  sports_kensaku_path, class: "link" %>
<%= link_to '投稿はこちらから',  new_sport_path, class: "link" %>